---
abstract: 'Extract namespaces/version from traditional packages for provides'
author:
  - 'Kent Fredric <kentnl@cpan.org>'
build_requires:
  Dist::Zilla::Util::Test::KENTNL: 0.01000011
  English: 0
  File::Find: 0
  Module::Build: 0.3601
  Test::Fatal: 0
  Test::Moose: 0
  Test::More: 0.96
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200004, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-Plugin-MetaProvides-Package
no_index:
  directory:
    - corpus
    - t/lib
provides:
  Dist::Zilla::Plugin::MetaProvides::Package:
    file: lib/Dist/Zilla/Plugin/MetaProvides/Package.pm
    version: 1.12060501
requires:
  Dist::Zilla::MetaProvides::ProvideRecord: 0
  Dist::Zilla::Plugin::MetaProvides: 1.12044806
  Dist::Zilla::Role::MetaProvider::Provider: 0
  File::Temp: 0
  Module::Extract::Namespaces: 0.14
  Module::Extract::VERSION: 0.13
  Moose: 0
  Moose::Autobox: 0
  namespace::autoclean: 0
resources:
  homepage: http://github.com/kentfredric/Dist-Zilla-Plugin-MetaProvides-Package/tree
  repository: git://github.com/kentfredric/Dist-Zilla-Plugin-MetaProvides-Package.git
version: 1.12060501
x_BuiltWith:
  modules:
    Dist::Zilla::MetaProvides::ProvideRecord: 1.12060212
    Dist::Zilla::Plugin::Bootstrap::lib: 0.01023600
    Dist::Zilla::Plugin::MetaNoIndex: 4.200004
    Dist::Zilla::Plugin::MetaProvides: 1.12060212
    Dist::Zilla::PluginBundle::Author::KENTNL: 1.0.5
    Dist::Zilla::PluginBundle::Author::KENTNL::Lite: 'NA(possibly not installed)'
    Dist::Zilla::Role::MetaProvider::Provider: 1.12060212
    Dist::Zilla::Util::Test::KENTNL: 0.01015821
    File::Temp: 0.22
    Module::Build: 0.38
    Module::Extract::Namespaces: 0.14
    Module::Extract::VERSION: 0.13
    Moose: 1.9906
    Moose::Autobox: 0.11
    Test::Fatal: 0.003
    Test::Moose: 1.9906
    Test::More: 0.98
    namespace::autoclean: 0.12
  perl:
    original: v5.12.3
    qv: 1
    version:
      - 5
      - 12
      - 3
  platform: linux
  uname: 'Linux 2.6.38-gentoo x86_64 GenuineIntel GNU/Linux'
x_Dist_Zilla:
  plugins:
    -
      class: Dist::Zilla::Plugin::AutoVersion::Relative
      config:
        Dist::Zilla::Plugin::AutoVersion::Relative:
          format: "{{ sprintf('%d.%02d%04d%02d', $major, $minor, days, hours) }}"
          major: 1
          minor: 12
          relative_to:
            day: 24
            hour: 0
            minute: 0
            month: 8
            second: 0
            time_zone: Pacific/Auckland
            year: 2009
      name: '@Author::KENTNL/AutoVersion::Relative'
      version: 0.01060309
    -
      class: Dist::Zilla::Plugin::GatherDir
      name: '@Author::KENTNL/GatherDir'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: '@Author::KENTNL/MetaConfig'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@Author::KENTNL/PruneCruft'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::GithubMeta
      name: '@Author::KENTNL/GithubMeta'
      version: 0.10
    -
      class: Dist::Zilla::Plugin::License
      name: '@Author::KENTNL/License'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::PkgVersion
      name: '@Author::KENTNL/PkgVersion'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::PodWeaver
      name: '@Author::KENTNL/PodWeaver'
      version: 3.101641
    -
      class: Dist::Zilla::Plugin::MetaProvides::Package
      name: '@Author::KENTNL/MetaProvides::Package'
      version: ~
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: '@Author::KENTNL/MetaJSON'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@Author::KENTNL/MetaYAML'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::ModuleBuild
      name: '@Author::KENTNL/ModuleBuild'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::ReadmeFromPod
      name: '@Author::KENTNL/ReadmeFromPod'
      version: 0.14
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@Author::KENTNL/ManifestSkip'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@Author::KENTNL/Manifest'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::AutoPrereqs
      name: '@Author::KENTNL/AutoPrereqs'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: develop
          type: requires
      name: '@Author::KENTNL/Prereqs/BundleDevelNeeds'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: develop
          type: recommends
      name: '@Author::KENTNL/Prereqs/BundleDevelRecommends'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: develop
          type: suggests
      name: '@Author::KENTNL/Prereqs/BundleDevelSuggests'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::MetaData::BuiltWith
      config:
        Dist::Zilla::Plugin::MetaData::BuiltWith:
          _stash_key: x_BuiltWith
          show_uname: 1
          uname:
            uname_args:
              - '-s'
              - '-o'
              - '-r'
              - '-m'
              - '-i'
            uname_call: uname
      name: '@Author::KENTNL/MetaData::BuiltWith'
      version: 0.01018204
    -
      class: Dist::Zilla::Plugin::CPANChangesTests
      name: '@Author::KENTNL/CPANChangesTests'
      version: 1.001
    -
      class: Dist::Zilla::Plugin::CompileTests
      name: '@Author::KENTNL/CompileTests'
      version: 1.110930
    -
      class: Dist::Zilla::Plugin::CriticTests
      name: '@Author::KENTNL/CriticTests'
      version: 1.102280
    -
      class: Dist::Zilla::Plugin::MetaTests
      name: '@Author::KENTNL/MetaTests'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::PodCoverageTests
      name: '@Author::KENTNL/PodCoverageTests'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: '@Author::KENTNL/PodSyntaxTests'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::ReportVersions::Tiny
      name: '@Author::KENTNL/ReportVersions::Tiny'
      version: 1.03
    -
      class: Dist::Zilla::Plugin::KwaliteeTests
      name: '@Author::KENTNL/KwaliteeTests'
      version: 1.101420
    -
      class: Dist::Zilla::Plugin::EOLTests
      name: '@Author::KENTNL/EOLTests'
      version: 0.02
    -
      class: Dist::Zilla::Plugin::ExtraTests
      name: '@Author::KENTNL/ExtraTests'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: '@Author::KENTNL/TestRelease'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: '@Author::KENTNL/ConfirmRelease'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::Git::Check
      name: '@Author::KENTNL/Git::Check'
      version: 1.110500
    -
      class: Dist::Zilla::Plugin::NextRelease
      name: '@Author::KENTNL/NextRelease'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::Git::Tag
      name: '@Author::KENTNL/Git::Tag/tag_master'
      version: 1.110500
    -
      class: Dist::Zilla::Plugin::Git::Commit
      name: '@Author::KENTNL/Git::Commit'
      version: 1.110500
    -
      class: Dist::Zilla::Plugin::Git::CommitBuild
      name: '@Author::KENTNL/Git::CommitBuild'
      version: 1.110500
    -
      class: Dist::Zilla::Plugin::Git::Tag
      name: '@Author::KENTNL/Git::Tag/tag_release'
      version: 1.110500
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@Author::KENTNL/UploadToCPAN'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::Twitter
      name: '@Author::KENTNL/Twitter'
      version: 0.010
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: runtime
          type: requires
      name: RuntimeRequires
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: test
          type: requires
      name: TestRequires
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: runtime
          type: suggests
      name: RuntimeSuggests
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: develop
          type: requires
      name: DevelopRequires
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: test
          type: suggests
      name: TestSuggests
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::MetaNoIndex
      name: MetaNoIndex
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: 4.200004
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: 0
    version: 4.200004
