---
abstract: 'Extract namespaces/version from traditional packages for provides'
author:
  - 'Kent Fredric <kentnl@cpan.org>'
build_requires:
  Dist::Zilla::Util::Test::KENTNL: 0.01000011
  Module::Build: 0.4204
  Test::Fatal: 0
  Test::Moose: 0
  Test::More: 1.001002
configure_requires:
  Module::Build: 0.4204
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.011, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-Plugin-MetaProvides-Package
no_index:
  directory:
    - corpus
    - t/lib
provides:
  Dist::Zilla::Plugin::MetaProvides::Package:
    file: lib/Dist/Zilla/Plugin/MetaProvides/Package.pm
    version: 1.15000003
requires:
  Data::Dump: 1.16
  Dist::Zilla::MetaProvides::ProvideRecord: 1.14000000
  Dist::Zilla::Plugin::FinderCode: 0
  Dist::Zilla::Plugin::MetaProvides: 1.15000000
  Dist::Zilla::Role::MetaProvider::Provider: 0
  IO::String: 0
  Module::Metadata: 1.000005
  Moose: 0
  Moose::Autobox: 0
  MooseX::LazyRequire: 0
  MooseX::Types::Moose: 0
  namespace::autoclean: 0
  perl: 5.010
  strict: 0
  utf8: 0
  warnings: 0
resources:
  bugtracker: https://github.com/kentfredric/Dist-Zilla-Plugin-MetaProvides-Package/issues
  homepage: https://github.com/kentfredric/Dist-Zilla-Plugin-MetaProvides-Package
  repository: https://github.com/kentfredric/Dist-Zilla-Plugin-MetaProvides-Package.git
version: 1.15000003
x_BuiltWith:
  modules:
    Data::Dump: 1.22
    Dist::Zilla::MetaProvides::ProvideRecord: 1.15000200
    Dist::Zilla::Plugin::Authority: 1.006
    Dist::Zilla::Plugin::AutoPrereqs: 5.011
    Dist::Zilla::Plugin::Bootstrap::lib: 0.04000002
    Dist::Zilla::Plugin::ConfirmRelease: 5.011
    Dist::Zilla::Plugin::EOLTests: 0.02
    Dist::Zilla::Plugin::FinderCode: 5.011
    Dist::Zilla::Plugin::Git::Check: 2.019
    Dist::Zilla::Plugin::Git::Commit: 2.019
    Dist::Zilla::Plugin::Git::CommitBuild: 2.019
    Dist::Zilla::Plugin::Git::GatherDir: 2.019
    Dist::Zilla::Plugin::Git::NextRelease: 0.001001
    Dist::Zilla::Plugin::Git::NextVersion::Sanitized: 0.001000
    Dist::Zilla::Plugin::Git::Tag: 2.019
    Dist::Zilla::Plugin::GithubMeta: 0.42
    Dist::Zilla::Plugin::License: 5.011
    Dist::Zilla::Plugin::Manifest: 5.011
    Dist::Zilla::Plugin::ManifestSkip: 5.011
    Dist::Zilla::Plugin::MetaConfig: 5.011
    Dist::Zilla::Plugin::MetaData::BuiltWith: 0.04000002
    Dist::Zilla::Plugin::MetaJSON: 5.011
    Dist::Zilla::Plugin::MetaNoIndex: 5.011
    Dist::Zilla::Plugin::MetaProvides: 1.15000200
    Dist::Zilla::Plugin::MetaProvides::Package: 1.15000003
    Dist::Zilla::Plugin::MetaTests: 5.011
    Dist::Zilla::Plugin::MetaYAML: 5.011
    Dist::Zilla::Plugin::MinimumPerl: 1.003
    Dist::Zilla::Plugin::ModuleBuild: 5.011
    Dist::Zilla::Plugin::PkgVersion: 5.011
    Dist::Zilla::Plugin::PodCoverageTests: 5.011
    Dist::Zilla::Plugin::PodSyntaxTests: 5.011
    Dist::Zilla::Plugin::PodWeaver: 4.005
    Dist::Zilla::Plugin::Prereqs: 5.011
    Dist::Zilla::Plugin::Prereqs::MatchInstalled: 0.1.6
    Dist::Zilla::Plugin::ReadmeAnyFromPod: 0.133360
    Dist::Zilla::Plugin::ReadmeFromPod: 0.21
    Dist::Zilla::Plugin::ReportVersions::Tiny: 1.10
    Dist::Zilla::Plugin::RunExtraTests: 0.016
    Dist::Zilla::Plugin::Test::CPAN::Changes: 0.008
    Dist::Zilla::Plugin::Test::Compile::PerFile: 0.001001
    Dist::Zilla::Plugin::Test::Kwalitee: 2.07
    Dist::Zilla::Plugin::Test::MinimumVersion: 2.000005
    Dist::Zilla::Plugin::Test::Perl::Critic: 2.112410
    Dist::Zilla::Plugin::TestRelease: 5.011
    Dist::Zilla::Plugin::Twitter: 0.024
    Dist::Zilla::Plugin::UploadToCPAN: 5.011
    Dist::Zilla::PluginBundle::Author::KENTNL: 2.008001
    Dist::Zilla::PluginBundle::Author::KENTNL::Lite: 1.7.2
    Dist::Zilla::Role::MetaProvider::Provider: 1.15000200
    Dist::Zilla::Util::Test::KENTNL: 0.01015824
    IO::String: 1.08
    Module::Build: 0.4204
    Module::Metadata: 1.000019
    Moose: 2.1201
    Moose::Autobox: 0.15
    MooseX::LazyRequire: 0.10
    MooseX::Types::Moose: 0.41
    Pod::Coverage::TrustPod: 0.100003
    Test::CPAN::Changes: 0.27
    Test::CPAN::Meta: 0.23
    Test::Fatal: 0.013
    Test::Kwalitee: 1.17
    Test::Moose: 2.1201
    Test::More: 1.001002
    Test::Pod: 1.48
    Test::Pod::Coverage: 1.08
    namespace::autoclean: 0.15
    strict: 1.08
    utf8: 1.13
    version: 0.9906
    warnings: 1.20
  perl:
    original: v5.19.7
    qv: 1
    version:
      - 5
      - 19
      - 7
  perl-config:
    gccversion: 4.7.3
    myarchname: x86_64-linux
    osname: linux
  platform: linux
  uname: 'Linux 3.12.0-gentoo x86_64 GenuineIntel GNU/Linux'
x_Dist_Zilla:
  perl:
    version: 5.019007
  plugins:
    -
      class: Dist::Zilla::Plugin::Bootstrap::lib
      config:
        Dist::Zilla::Role::Bootstrap:
          distname: Dist-Zilla-Plugin-MetaProvides-Package
          fallback: 0
          try_built: 1
          try_built_method: mtime
      name: Bootstrap::lib
      version: 0.04000002
    -
      class: Dist::Zilla::Plugin::Git::NextVersion::Sanitized
      config:
        Dist::Zilla::Role::Version::Sanitize:
          mantissa: 8
          normal_form: numify
      name: '@Author::KENTNL/Git::NextVersion::Sanitized'
      version: 0.001000
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: '@Author::KENTNL/MetaConfig'
      version: 5.011
    -
      class: Dist::Zilla::Plugin::GithubMeta
      name: '@Author::KENTNL/GithubMeta'
      version: 0.42
    -
      class: Dist::Zilla::Plugin::MetaProvides::Package
      config:
        Dist::Zilla::Plugin::MetaProvides::Package:
          finder_objects:
            -
              class: Dist::Zilla::Plugin::FinderCode
              name: '@Author::KENTNL/MetaProvides::Package/AUTOVIV/:InstallModulesPM'
              version: 5.011
        Dist::Zilla::Role::MetaProvider::Provider:
          inherit_missing: 1
          inherit_version: 1
          meta_noindex: 1
      name: '@Author::KENTNL/MetaProvides::Package'
      version: 1.15000003
    -
      class: Dist::Zilla::Plugin::MetaData::BuiltWith
      config:
        Dist::Zilla::Plugin::MetaData::BuiltWith:
          _stash_key: x_BuiltWith
          show_config: 1
          show_uname: 1
          uname:
            uname_args:
              - '-s'
              - '-o'
              - '-r'
              - '-m'
              - '-i'
            uname_call: uname
      name: '@Author::KENTNL/MetaData::BuiltWith'
      version: 0.04000002
    -
      class: Dist::Zilla::Plugin::Git::GatherDir
      name: '@Author::KENTNL/Git::GatherDir'
      version: 2.019
    -
      class: Dist::Zilla::Plugin::License
      name: '@Author::KENTNL/License'
      version: 5.011
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: '@Author::KENTNL/MetaJSON'
      version: 5.011
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@Author::KENTNL/MetaYAML'
      version: 5.011
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@Author::KENTNL/Manifest'
      version: 5.011
    -
      class: Dist::Zilla::Plugin::MetaTests
      name: '@Author::KENTNL/MetaTests'
      version: 5.011
    -
      class: Dist::Zilla::Plugin::PodCoverageTests
      name: '@Author::KENTNL/PodCoverageTests'
      version: 5.011
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: '@Author::KENTNL/PodSyntaxTests'
      version: 5.011
    -
      class: Dist::Zilla::Plugin::ReportVersions::Tiny
      name: '@Author::KENTNL/ReportVersions::Tiny'
      version: 1.10
    -
      class: Dist::Zilla::Plugin::Test::Kwalitee
      name: '@Author::KENTNL/Test::Kwalitee'
      version: 2.07
    -
      class: Dist::Zilla::Plugin::EOLTests
      name: '@Author::KENTNL/EOLTests'
      version: 0.02
    -
      class: Dist::Zilla::Plugin::Test::MinimumVersion
      name: '@Author::KENTNL/Test::MinimumVersion'
      version: 2.000005
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: '@Author::KENTNL/Test::Compile::PerFile/AUTOVIV/:InstallModulesPM'
      version: 5.011
    -
      class: Dist::Zilla::Plugin::Test::Compile::PerFile
      config:
        Dist::Zilla::Plugin::Test::Compile::PerFile:
          file:
            - lib/Dist/Zilla/Plugin/MetaProvides/Package.pm
          path_translator: base64_filter
          prefix: t/00-compile
          skip: []
          test_template: 01-basic.t.tpl
          xt_mode: ~
      name: '@Author::KENTNL/Test::Compile::PerFile'
      version: 0.001001
    -
      class: Dist::Zilla::Plugin::Test::Perl::Critic
      name: '@Author::KENTNL/Test::Perl::Critic'
      version: 2.112410
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@Author::KENTNL/ManifestSkip'
      version: 5.011
    -
      class: Dist::Zilla::Plugin::PkgVersion
      name: '@Author::KENTNL/PkgVersion'
      version: 5.011
    -
      class: Dist::Zilla::Plugin::PodWeaver
      config:
        Dist::Zilla::Plugin::PodWeaver:
          finder:
            - ':InstallModules'
            - ':ExecFiles'
          plugins:
            -
              class: Pod::Weaver::Plugin::EnsurePod5
              name: '@CorePrep/EnsurePod5'
              version: 4.006
            -
              class: Pod::Weaver::Plugin::H1Nester
              name: '@CorePrep/H1Nester'
              version: 4.006
            -
              class: Pod::Weaver::Plugin::SingleEncoding
              name: '-SingleEncoding'
              version: 4.006
            -
              class: Pod::Weaver::Section::Name
              name: Name
              version: 4.006
            -
              class: Pod::Weaver::Section::Version
              name: Version
              version: 4.006
            -
              class: Pod::Weaver::Section::Region
              name: prelude
              version: 4.006
            -
              class: Pod::Weaver::Section::Generic
              name: SYNOPSIS
              version: 4.006
            -
              class: Pod::Weaver::Section::Generic
              name: DESCRIPTION
              version: 4.006
            -
              class: Pod::Weaver::Section::Generic
              name: NAMING_SCHEME
              version: 4.006
            -
              class: Pod::Weaver::Section::Generic
              name: OVERVIEW
              version: 4.006
            -
              class: Pod::Weaver::Section::Collect
              name: ROLES
              version: 4.006
            -
              class: Pod::Weaver::Section::Collect
              name: ROLEMETHODS
              version: 4.006
            -
              class: Pod::Weaver::Section::Collect
              name: METHODS
              version: 4.006
            -
              class: Pod::Weaver::Section::Collect
              name: ATTRIBUTES
              version: 4.006
            -
              class: Pod::Weaver::Section::Collect
              name: PRIVATE_ATTRIBUTES
              version: 4.006
            -
              class: Pod::Weaver::Section::Collect
              name: PRIVATE_METHODS
              version: 4.006
            -
              class: Pod::Weaver::Section::Leftovers
              name: Leftovers
              version: 4.006
            -
              class: Pod::Weaver::Section::Region
              name: postlude
              version: 4.006
            -
              class: Pod::Weaver::Section::Authors
              name: Authors
              version: 4.006
            -
              class: Pod::Weaver::Section::Legal
              name: Legal
              version: 4.006
      name: '@Author::KENTNL/PodWeaver'
      version: 4.005
    -
      class: Dist::Zilla::Plugin::Git::NextRelease
      name: '@Author::KENTNL/Git::NextRelease'
      version: 0.001001
    -
      class: Dist::Zilla::Plugin::AutoPrereqs
      name: '@Author::KENTNL/AutoPrereqs'
      version: 5.011
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: develop
          type: suggests
      name: '@Author::KENTNL/BundleDevelSuggests'
      version: 5.011
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: develop
          type: requires
      name: '@Author::KENTNL/BundleDevelRequires'
      version: 5.011
    -
      class: Dist::Zilla::Plugin::MinimumPerl
      name: '@Author::KENTNL/MinimumPerl'
      version: 1.003
    -
      class: Dist::Zilla::Plugin::Authority
      name: '@Author::KENTNL/Authority'
      version: 1.006
    -
      class: Dist::Zilla::Plugin::ModuleBuild
      name: '@Author::KENTNL/ModuleBuild'
      version: 5.011
    -
      class: Dist::Zilla::Plugin::ReadmeFromPod
      name: '@Author::KENTNL/ReadmeFromPod'
      version: 0.21
    -
      class: Dist::Zilla::Plugin::ReadmeAnyFromPod
      name: '@Author::KENTNL/ReadmeAnyFromPod'
      version: 0.133360
    -
      class: Dist::Zilla::Plugin::Test::CPAN::Changes
      name: '@Author::KENTNL/Test::CPAN::Changes'
      version: 0.008
    -
      class: Dist::Zilla::Plugin::RunExtraTests
      name: '@Author::KENTNL/RunExtraTests'
      version: 0.016
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: '@Author::KENTNL/TestRelease'
      version: 5.011
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: '@Author::KENTNL/ConfirmRelease'
      version: 5.011
    -
      class: Dist::Zilla::Plugin::Git::Check
      name: '@Author::KENTNL/Git::Check'
      version: 2.019
    -
      class: Dist::Zilla::Plugin::Git::Tag
      name: '@Author::KENTNL/tag_master'
      version: 2.019
    -
      class: Dist::Zilla::Plugin::Git::Commit
      name: '@Author::KENTNL/Git::Commit'
      version: 2.019
    -
      class: Dist::Zilla::Plugin::Git::CommitBuild
      name: '@Author::KENTNL/Git::CommitBuild'
      version: 2.019
    -
      class: Dist::Zilla::Plugin::Git::Tag
      name: '@Author::KENTNL/tag_release'
      version: 2.019
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@Author::KENTNL/UploadToCPAN'
      version: 5.011
    -
      class: Dist::Zilla::Plugin::Twitter
      name: '@Author::KENTNL/Twitter'
      version: 0.024
    -
      class: Dist::Zilla::Plugin::Prereqs::MatchInstalled
      config:
        Dist::Zilla::Plugin::Prereqs::MatchInstalled:
          applyto:
            - build.requires
            - build.recommends
            - build.suggests
            - test.requires
            - test.recommends
            - test.suggests
            - runtime.requires
            - runtime.recommends
            - runtime.suggests
            - configure.requires
            - configure.recommends
            - configure.suggests
            - develop.requires
            - develop.recommends
            - develop.suggests
          applyto_phase:
            - build
            - test
            - runtime
            - configure
            - develop
          applyto_relation:
            - requires
            - recommends
            - suggests
          modules:
            - Module::Build
            - Test::More
            - Dist::Zilla::PluginBundle::Author::KENTNL
      name: '@Author::KENTNL/Prereqs::MatchInstalled'
      version: 0.1.6
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: develop
          type: requires
      name: '@Author::KENTNL/::Role::BundleDeps'
      version: 5.011
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: runtime
          type: requires
      name: RuntimeRequires
      version: 5.011
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: runtime
          type: suggests
      name: RuntimeSuggests
      version: 5.011
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: develop
          type: requires
      name: DevelopRequires
      version: 5.011
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: test
          type: suggests
      name: TestSuggests
      version: 5.011
    -
      class: Dist::Zilla::Plugin::MetaNoIndex
      name: MetaNoIndex
      version: 5.011
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: 5.011
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':IncModules'
      version: 5.011
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: 5.011
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: 5.011
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: 5.011
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':MainModule'
      version: 5.011
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':AllFiles'
      version: 5.011
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':NoFiles'
      version: 5.011
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: '@Author::KENTNL/MetaProvides::Package/AUTOVIV/:InstallModulesPM'
      version: 5.011
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: 0
    version: 5.011
x_authority: cpan:KENTNL
